name: Conventional Commits
on: 
  push:
    branches:
    - master

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    environment: sec-env
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - uses: webiny/action-conventional-commits@v1.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      - name: Release
        env: 
         GITHUB_TOKEN : ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
        
      
